# Personal machine profile configuration
# This profile is optimized for personal productivity and entertainment

profile:
  name: "personal"
  description: "Personal machine setup"

# Package management
homebrew:
  formulas:
    # Essential tools
    - git
    - jq
    - curl
    - wget
    - tree
    - bat
    - htop
    
    # Light development
    - node
    - python3
    
  casks:
    # Productivity
    - bitwarden
    - spotify
    - iina
    - betterzip
    - openaudible
    - setapp
    - notion
    - raycast
    
    # Communication
    - slack
    - zoom
    - whatsapp
    - telegram
    
    # Creative and media
    - calibre
    - google-chrome
    
    # AI tools
    - chatgpt

# Mac App Store applications
mas_apps:
  - id: 472226235
    name: "LanScan"
  - id: 904280696
    name: "Things 3"
  - id: 441258766
    name: "Magnet"

# Configuration
config:
  skip_xcode: true
  skip_homebrew: false
  skip_mas_apps: false
  skip_ruby_install: true
  skip_python_install: true
  skip_node_install: true
  
  # Terminal setup
  enable_powerline: true
  enable_autosuggestions: true
  enable_syntax_highlighting: true
  theme: "Highway"
  setup_custom_terminal: true